---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart searxng container
  ansible.builtin.systemd:
    name: searxng-container.service
    state: restarted

- name: Restart searxng-mcp container
  ansible.builtin.systemd:
    name: searxng-mcp-container.service
    state: restarted
