---
- name: Create paperless paths
  ansible.builtin.file:
    path: "{{ item_path }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0770"
  loop:
    - "{{ paperless_path }}"
    - "{{ paperless_data_path }}"
    - "{{ paperless_media_path }}"
    - "{{ paperless_export_path }}"
    - "{{ paperless_consume_path }}"

  loop_control:
    loop_var: item_path

- name: Paperless Service
  ansible.builtin.template:
    src: paperless_ngx.service.j2
    dest: "/etc/systemd/system/paperless_ngx.service"

- name: Enable paperless
  ansible.builtin.systemd:
    name: paperless_ngx.service
    enabled: yes

- name: Paperless script
  ansible.builtin.template:
    src: paperless_ngx.sh.j2
    dest: "/usr/local/bin/paperless_ngx.sh"
    owner: "{{ user_name }}"
    group: root
    mode: "0770"

- name: Install zip and jq packages
  ansible.builtin.dnf:
    name:
      - zip
      - jq
    state: present
